Chapter18/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

Chapter18/pizzeria/pizzas/urls.py
"""Define the url patterns for pizzas app"""

from django.urls import path

from pizzas import views

app_name = 'pizzas'
urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas/', views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
]

Chapter18/pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('pizzas.urls'))
]

Chapter18/users/urls.py
from django.urls import path, include
from users import views

app_name = 'users'
urlpatterns = [
    # include default auth urls
    path('', include("django.contrib.auth.urls")),
    path('register/', views.register, name='register'),
]

Chapter18/pizzeria/pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    """a specific pizza"""
    name = models.CharField(max_length=200)
    data_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """representation of pizza"""
        return self.name

class Topping(models.Model):
    """specific toppings"""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    data_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """representation of pizza"""
        return self.name

Chapter18/pizzeria/pizzas/views.py
from django.shortcuts import render
from pizzas.models import Pizza, Topping

# Create your views here.
def index(request):
    """render the home page"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """show all pizzas"""
    pizzas = Pizza.objects.all()
    context = {
        'pizzas': pizzas
    }
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """show the detail of pizza"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()
    context = {
        'pizza': pizza,
        'toppings': toppings,
    }
    return render(request, 'pizzas/pizza.html', context)

Chapter18/pizzeria/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Home</a> - 
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}
{% endblock content %}

Chapter18/pizzeria/pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% block content %}

<title>sfsdf</title>
<p>sdf<br>sdf </br>sdf </p>

{% endblock content %}

Chapter18/pizzeria/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

<p>{{ pizza }}</p>

<ul>
    {% for topping in toppings %}
        <li>
            {{ topping }}
        </li>
    {% empty %}
        <p>There are no toppings!</p>
    {% endfor %}
</ul>

{% endblock content %}

Chapter18/pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}
        <li>
            <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
        </li>
    {% empty %}
        <p>There are no pizzas!</p>
    {% endfor %}
</ul>

{% endblock content %}