Chapter19/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls'))
]

Chapter19/blog/blogs/urls.py
from django.urls import path
from blogs import views

app_name = 'blogs'
urlpatterns = [
    path('', views.posts, name='posts'),
    path('post/<int:post_id>/', views.post, name='post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('add_post/', views.add_post, name='add_post'),
]

Chapter19/blog/users/urls.py
from django.urls import path, include
from users import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

Chapter19/blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogPost(models.Model):
    """modeling blog post"""
    title = models.CharField(max_length=50)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """represent the post"""
        if len(self.text) < 50:
            return self.text
        else:
            return self.text[:50] + '...'

Chapter19/blog/users/models.py
from django.db import models

# Create your models here.

Chapter19/blog/blogs/forms.py
from django.forms import ModelForm
from blogs.models import BlogPost

class PostForm(ModelForm):
    """define the post form """

    class Meta:
        model = BlogPost
        fields = [
            'title',
            'text',
        ]

Chapter19/blog/blogs/views.py
from django.shortcuts import render, redirect
from blogs.models import BlogPost
from blogs.forms import PostForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

def check_object_owner(request, item):
    """check the item belongs to the login user"""
    if request.user != item.owner:
        raise Http404

# Create your views here.
@login_required
def posts(request):
    """show the all of posts"""

    posts = BlogPost.objects.filter(owner=request.user).order_by('-timestamp')
    context = {
        'posts': posts
    }

    return render(request, 'blogs/posts.html', context)

@login_required
def post(request, post_id):
    """show the detail of post"""
    post = BlogPost.objects.get(id=post_id)
    check_object_owner(request, post)
    context = {
        'post': post
    }
    return render(request, 'blogs/post.html', context)

@login_required
def edit_post(request, post_id):
    """show the detail of post"""
    post = BlogPost.objects.get(id=post_id)
    check_object_owner(request, post)

    if request.method != 'POST':
        form = PostForm(instance=post)
    else:
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:post', post.id)

    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'blogs/edit_post.html', context)

@login_required
def add_post(request):
    """show the detail of post"""

    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('blogs:posts')
    context = {
        'form': form,
    }
    return render(request, 'blogs/add_post.html', context)

Chapter19/blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

# Create your views here.
def register(request):
    """register a new user"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('blogs:posts')

    context = {
        'form': form
    }

    return render(request, 'registration/register.html', context)

Chapter19/blog/blogs/templates/blogs/add_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}


{% block content %}


<form action="{% url 'blogs:add_post' %}" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button method='submit' class="btn btn-primary">
        Create
    </button>
    {% endbuttons %}
    
</form>

{% endblock content %}

Chapter19/blog/blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>
            Sage's Blog
        </title>
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <a class="navbar-brand" href="{% url 'blogs:posts' %}">
                Sage's Blog
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">

                </span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text">
                                Hello, {{ user.username }}
                            </span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">
                                Logout
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">
                                Register
                            </a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:login' %}">
                                    Login
                                </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}
                {% endblock page_header %}
            </div>

            <div>
                {% block content %}
                {% endblock content %}
            </div>
        </main>
    </body>
</html>

Chapter19/blog/blogs/templates/blogs/edit_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block content %}

<form action="{% url 'blogs:edit_post' post.id %}" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button method='submit' class="btn btn-primary">
        Save
    </button>
    {% endbuttons %}

</form>

{% endblock content %}

Chapter19/blog/blogs/templates/blogs/post.html
{% extends 'blogs/base.html' %}

{% block page_header %}
    <h2>
        {{ post.title }}
    </h2>
{% endblock page_header %}

{% block content %}

    <p>
        <a href="{% url 'blogs:edit_post' post.id %}">Edit</a>
    </p>

    <div class="jumbotron" style="word-wrap:break-word; ">
        <p>
            {{ post.text | linebreaks }}
        </p>
    </div>

{% endblock content %}

Chapter19/blog/blogs/templates/blogs/posts.html
{% extends 'blogs/base.html' %}

{% block page_header %}
    <h3>Post List</h3>
{% endblock page_header %}


{% block content %}

    <p>
        <a href="{% url 'blogs:add_post' %}">Add post</a>
    </p>

    {% for post in posts %}
        <div class="card mb-3">
            <h4 class="card-header">
                <a href="{% url 'blogs:post' post.id %}">{{ post.title }}</a>
                <small>
                    {{ post.timestamp | date:'Y-m-d H:i' }}
                </small>
            </h4>

            <div class="card-body">
                    {{ post|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>
            There are nothing posts!
        </p>
    {% endfor %}


{% endblock content %}